### ISSUE TITLE
Ignoring proxy options

### ISSUE THREAD

**Issue by nxshock** [kitech/go-toxcore#1]
I'm trying to set up a client to use a proxy (Tor), but it appears that the client ignores the proxy settings and connects directly. Example:
```
opt := tox.NewToxOptions()
opt.Ipv6_enabled = false
opt.Udp_enabled = false
opt.Proxy_type = 2
opt.Proxy_address = "127.0.0.1"
opt.Proxy_port = 9050
opt.Tcp_port = 0
t := tox.NewTox(opt)
```

**Comment by kitech** [comment]
Yes, sorry for not very complete implentioned.
I will try do that today.
thanks

**Comment by nxshock** [comment]
Looks like now proxy works. Good job!

**Comment by kitech** [comment]
OK.
