### ISSUE TITLE
SelfGetName and SelfGetStatusMessage will cause error!

### ISSUE THREAD

**Issue by xbee** [kitech/go-toxcore#10]
in toxecho.go SelfGetName and SelfGetStatusMessage will cause runtime error, but if I add two lines code in func NewTox(opt *ToxOptions) *Tox 

```
// set default name and status
tox.SelfSetName("NickName")
tox.SelfSetStatusMessage("Offline")
```

it will woking.

**Comment by nxshock** [comment]
+1, same issue in my tests.

**Comment by kitech** [comment]
should be fixed. zero length buffer index out of range.
