### ISSUE TITLE
Update "group" to "conference" API & update to stateless callbacks.

### ISSUE THREAD

**Issue by iphydf** [kitech/go-toxcore#4]
In https://github.com/TokTok/c-toxcore we have made old group chats a first class supported API and rebranded it as conference. The new group chats will be called "group". We have also removed user data from callback registration functions. This now needs to be passed to `tox_iterate`. It seems you don't use that anyway, so you can just remove one nil-argument from those calls.

**Comment by kitech** [comment]
Both of your point are nice.
First, I want wait for toxcore/new branch, but seems long time to wait.
Second, seems user data is useless, should be changed.

**Comment by kitech** [comment]
master switched to toktok/c-toxcore.
